packages/web/src/components/organisms/OrderDetail/OrderDetail.stories.tsx
packages/web/src/components/organisms/OrderDetail/OrderDetail.tsx
packages/web/src/components/organisms/OrderDetail/index.ts
packages/web/src/components/templates/Order/Order.stories.tsx
packages/web/src/components/templates/Order/Order.tsx
packages/web/src/components/templates/Order/index.ts
packages/web/src/pages/orders/[orderId].tsx

chore: added order page

---

packages/contracts/test/serport.spec.ts
packages/web/package.json
packages/web/src/components/molecules/ConnectedWallet/ConnectedWallet.tsx
packages/web/src/components/organisms/NFTDetail/NFTDetail.stories.tsx
packages/web/src/components/organisms/NFTDetail/NFTDetail.tsx
packages/web/src/components/templates/NFT/NFT.stories.tsx
packages/web/src/components/templates/NFT/NFT.tsx
packages/web/src/lib/order/index.ts
packages/web/src/pages/accounts/[walletAddress]/index.tsx
packages/web/src/pages/nfts/[chainId]/[contractAddress]/[tokenId].tsx
yarn.lock

Integrated from 7018a0710ec1c6208cfb18eabcf2c0e2412f1c73
close #26

chore: added seaport order in web

---

.github/workflows/chromatic.yml
packages/web/package.json
yarn.lock

chore: setup chromatic

---

packages/web/src/components/organisms/NFTDetail/NFTDetail.tsx
packages/web/src/components/organisms/NFTRegister/NFTRegister.stories.tsx
packages/web/src/components/organisms/NFTRegister/NFTRegister.tsx
packages/web/src/components/organisms/NFTRegister/index.ts
packages/web/src/components/templates/Account/Account.tsx

feat: add nft from mypage

---

packages/web/src/components/molecules/ConnectedWallet/ConnectedWallet.tsx

feat: mypage button

---

packages/web/src/components/molecules/DropdownSelectNetwork/DropdownSelectNetwork.tsx
packages/web/src/components/organisms/Header/Header.tsx

fix: mobile view of navbar

---

packages/web/src/components/molecules/ConnectWalletButton/ConnectWalletButton.tsx

This seems that the connector differs on the server-side and front.
This PR may be a temp solution for others to start developing other parts.

fix: fix #95

---

packages/web/src/components/organisms/NFTDetail/NFTDetail.tsx

feat: resolve #47

---

firestore.rules

This should be enough since we are not handling write from frontend.

feat: resolve #83

---

packages/common/configs/app.ts
packages/functions/src/functions/cleaning.ts
packages/functions/src/functions/nft.ts
packages/functions/src/functions/order.ts
packages/functions/src/lib/functions.ts
packages/web/src/lib/firebase/index.ts

close #138
changed
- functions
- web

feat: change europe region

---

packages/web/src/components/organisms/NFTDetail/NFTDetail.tsx

feat: resolve #153

---

packages/web/src/components/molecules/Notification/Notification.stories.tsx
packages/web/src/components/molecules/Notification/Notification.tsx
packages/web/src/components/molecules/Notification/index.ts
packages/web/src/components/organisms/NFTDetail/NFTDetail.tsx
packages/web/src/components/organisms/OrderDetail/OrderDetail.tsx

feat: resove #103 notification

---

packages/common/entities/nft/type.ts
packages/common/entities/order/type.ts
packages/common/value-objects/record.ts
packages/common/value-objects/timestamp.ts
packages/functions/src/functions/nft.ts
packages/functions/src/functions/order.ts
packages/web/src/components/organisms/NFTDetail/NFTDetail.tsx
packages/web/src/components/organisms/OrderList/OrderList.tsx
packages/web/src/pages/index.tsx
packages/web/src/pages/nfts/[chainId]/[contractAddress]/[tokenId].tsx
packages/web/src/pages/orders/[orderId].tsx

This is implementing ISR for better performance

feat: resolve #169

---

package.json
packages/web/iframe/nft.html
packages/web/package.json
yarn.lock

close #160
Just tested iframe and web3 wallet is working nice.

feat: test iframe

---

packages/web/src/components/organisms/NFTList/NFTList.tsx
packages/web/src/components/organisms/OrderList/OrderList.tsx
packages/web/src/components/templates/Home/Home.tsx
packages/web/src/pages/nfts/[chainId]/[contractAddress]/[tokenId].tsx

close #186
Just implemented UI
SImple one line covers all issues.

feat: implement toppage

---

packages/functions/src/functions/nft.ts
packages/functions/src/functions/royalty.ts
packages/functions/src/index.ts
packages/sdk/contracts/__import__/OpenZeppelin.sol
packages/web/src/pages/nfts/[chainId]/[contractAddress]/[tokenId].tsx
yarn.lock

feat: add royalty query endpoint

---

packages/hasura/metadata/cron_triggers.yaml
packages/next-app/src/components/molecules/AddNFT/AddNFT.tsx
packages/next-app/src/pages/api/order/cleaning.ts

order cleaning

---

.github/actions/setup/action.yml
.github/workflows/ci.yml
README.md
docker-compose.yml
package.json
packages/hardhat/hardhat.config.ts
packages/hardhat/test/utils/setup.ts
packages/hardhat/tsconfig.json
packages/hasura/metadata/databases/default/tables/public_assets.yaml
packages/hasura/metadata/databases/default/tables/public_contracts.yaml
packages/hasura/metadata/databases/default/tables/public_validOrders.yaml
packages/hasura/src/lib/apollo/index.ts
packages/hasura/src/lib/sequelize/index.ts
packages/hasura/src/types/order.ts
packages/next-app/.env.production
packages/next-app/.eslintrc.json
packages/next-app/next.config.js
packages/next-app/src/components/atoms/Link/Link.stories.tsx
packages/next-app/src/hooks/useSwap.tsx
packages/next-app/src/pages/_app.tsx
packages/next-app/src/pages/api/asset/sync.ts
packages/next-app/src/pages/assets/[chainId]/[contractAddress]/[tokenId].tsx
packages/shared/src/configs/app.ts
yarn.lock

chore: update ci

---

packages/hardhat/test/sdk.spec.ts

fix: build error for test

---

packages/next-app/src/components/organisms/AddAsset/AddAsset.tsx
packages/next-app/src/components/organisms/Assets/Assets.stories.tsx
packages/next-app/src/components/organisms/Assets/Assets.tsx
packages/next-app/src/pages/index.tsx
vercel.json

close #262 
https://user-images.githubusercontent.com/45842611/180358869-7d1fcc0b-6df1-4274-ba38-8278c2a42cfb.mov

fix: improve loader

---

packages/hasura/src/lib/apollo/index.ts
packages/hasura/src/lib/hasura/type.ts
packages/hasura/src/lib/hasura/util.ts
packages/next-app/src/components/organisms/Assets/Assets.tsx
packages/next-app/src/components/templates/Assets/Assets.tsx
packages/next-app/src/components/templates/Home/Home.tsx
packages/next-app/src/pages/assets/index.tsx
packages/next-app/src/pages/index.tsx

some loading tuning for better performance and clean code
- remove un necessary variables 
- use typePolicies instead of update query
close #271

Improve loading
